ejercicio3: ejercicio3.cpp Rectangulo.o Ortoedro.o 
	g++ ejercicio3.cpp Ortoedro.o Rectangulo.o Coordenada.o -o p3
Ortoedro.o: Ortoedro.cpp Rectangulo.o Ortoedro.h	
	g++ Ortoedro.cpp -c
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
	g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c	